package mockserver_test

import (
	"crypto/tls"
	"io"
	nethttp "net/http"
	"strings"
	"testing"
	"time"

	"livecharge/loadtest/internal/config"
	"livecharge/loadtest/internal/mockserver"
)

func TestMockTLS_AutoGenerated_RoundTrip(t *testing.T) {
	cfg := config.MockConfig{
		Transport: config.TransportConfig{
			Type: "http",
			URL:  "127.0.0.1:0",
			TLS:  &config.TLSConfig{Enabled: true},
		},
		Endpoints: []config.MockEndpointConfig{{
			Path: "/", Method: "GET", OkResponse: "hello",
		}},
	}
	srv, err := mockserver.NewMockServer(cfg)
	if err != nil {
		t.Fatalf("NewMockServer: %v", err)
	}
	if err := srv.Start(); err != nil {
		t.Fatalf("Start: %v", err)
	}
	defer srv.Stop()

	addr := srv.Addr()
	if addr == "" {
		t.Fatal("Addr() returned empty after Start")
	}

	client := &nethttp.Client{
		Transport: &nethttp.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		},
		Timeout: 2 * time.Second,
	}
	resp, err := client.Get("https://" + addr + "/")
	if err != nil {
		t.Fatalf("GET: %v", err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	if !strings.Contains(string(body), "hello") {
		t.Errorf("body = %q", string(body))
	}
}
