package mockserver_test

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"io"
	"math/big"
	nethttp "net/http"
	"os"
	"strings"
	"testing"
	"time"

	"livecharge/loadtest/internal/config"
	"livecharge/loadtest/internal/mockserver"
)

func TestMockTLS_AutoGenerated_RoundTrip(t *testing.T) {
	cfg := config.MockConfig{
		Transport: config.TransportConfig{
			Type: "http",
			URL:  "127.0.0.1:0",
			TLS:  &config.TLSConfig{Enabled: true},
		},
		Endpoints: []config.MockEndpointConfig{{
			Path: "/", Method: "GET", OkResponse: "hello",
		}},
	}
	srv, err := mockserver.NewMockServer(cfg)
	if err != nil {
		t.Fatalf("NewMockServer: %v", err)
	}
	if err := srv.Start(); err != nil {
		t.Fatalf("Start: %v", err)
	}
	defer srv.Stop()

	addr := srv.Addr()
	if addr == "" {
		t.Fatal("Addr() returned empty after Start")
	}

	client := &nethttp.Client{
		Transport: &nethttp.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		},
		Timeout: 2 * time.Second,
	}
	resp, err := client.Get("https://" + addr + "/")
	if err != nil {
		t.Fatalf("GET: %v", err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	if !strings.Contains(string(body), "hello") {
		t.Errorf("body = %q", string(body))
	}
}

func TestMockTLS_UserSuppliedCert(t *testing.T) {
	dir := t.TempDir()
	certPath, keyPath := writeTestCert(t, dir, "loadtest-test-cert")

	cfg := config.MockConfig{
		Transport: config.TransportConfig{
			Type: "http",
			URL:  "127.0.0.1:0",
			TLS: &config.TLSConfig{
				Enabled:  true,
				CertFile: certPath,
				KeyFile:  keyPath,
			},
		},
		Endpoints: []config.MockEndpointConfig{{Path: "/", Method: "GET", OkResponse: "ok"}},
	}
	srv, err := mockserver.NewMockServer(cfg)
	if err != nil {
		t.Fatal(err)
	}
	if err := srv.Start(); err != nil {
		t.Fatal(err)
	}
	defer srv.Stop()

	client := &nethttp.Client{Transport: &nethttp.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}, Timeout: 2 * time.Second}
	resp, err := client.Get("https://" + srv.Addr() + "/")
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
}

// writeTestCert writes a fresh self-signed cert+key to disk and returns
// the two paths. Mirrors cert.go's crypto choices for consistency.
func writeTestCert(t *testing.T, dir, cn string) (certPath, keyPath string) {
	t.Helper()
	priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("genkey: %v", err)
	}
	serial, _ := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	tmpl := &x509.Certificate{
		SerialNumber: serial,
		Subject:      pkix.Name{CommonName: cn},
		NotBefore:    time.Now().Add(-time.Minute),
		NotAfter:     time.Now().Add(time.Hour),
		KeyUsage:     x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &priv.PublicKey, priv)
	if err != nil {
		t.Fatalf("createcert: %v", err)
	}

	certPath = dir + "/cert.pem"
	keyPath = dir + "/key.pem"
	certFile, _ := os.Create(certPath)
	pem.Encode(certFile, &pem.Block{Type: "CERTIFICATE", Bytes: der})
	certFile.Close()
	keyBytes, _ := x509.MarshalECPrivateKey(priv)
	keyFile, _ := os.Create(keyPath)
	pem.Encode(keyFile, &pem.Block{Type: "EC PRIVATE KEY", Bytes: keyBytes})
	keyFile.Close()
	return certPath, keyPath
}
